language: go
dist: zesty
go:
  - 1.9

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/mattn/goveralls
  - sudo apt-get update
  - sudo apt-get install -y build-essential libgtk-3-dev libcairo2-dev libglib2.0-dev

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go test -coverprofile=coverage.txt ./pwsafe

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci
