language: go
dist: trusty
go:
  - 1.5

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential libgtk2.0-dev
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls

script:
    - go vet -x ./...
    - $HOME/gopath/bin/golint ./...
    - go test -v -race ./...
    - go test -coverprofile=profile.cov ./pwsafe

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
