language: go
go:
  - tip

sudo: false
matrix:
    fast_finish: true

before_install:
    - apt-get install build-essential
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls

script:
    - go vet -x ./...
    - $HOME/gopath/bin/golint ./...
    - go test -v -race ./...
    - go test -coverprofile=profile.cov ./pwsafe

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
