language: go
go:
  - 1.9

services:
  - docker
sudo: required

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/mattn/goveralls
  - docker pull golang:1.9
  - echo "#!/bin/sh -e" > build.sh
  - echo "apt-get update" >> build.sh
  - echo "apt-get install -y build-essential libgtk-3-dev libcairo2-dev libglib2.0-dev" >> build.sh
  - echo 'go test -v -race $(go list ./... | grep -v "/vendor/")' >> build.sh
  - echo "go test -coverprofile=coverage.txt ./pwsafe" >> build.sh
  - chmod +x build.sh

script:
  - docker run --rm -v "$GOPATH":/go -w /go/src/github.com/tkuhlman/gopwsafe golang:1.9 ./build.sh

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci
